### ISSUE TITLE
Run docker in rootless mode

### ISSUE THREAD

**Issue by RequestPrivacy** [kycfree1/x86-Bitcoin-Node-Guide#3]
In the guide you run docker services in rootfull mode (i.e. the "normal" way).

I would discourage this kind of usage on a bare metal server (not so much an issue if every service has its own virtual machine). 
Rootless mode has serious security implications. I've written some lines you might want to check out: [Bitcoin and Docker - A match (not) made in heaven](https://github.com/RequestPrivacy/rootlessDocker).

I tested your guide with rootless mode and it works well although housekeeping increases (multiple users, a bit more setup, some change of folder ownerships).

I'd say it would increase the steps/volume of your guide by about 15%.

For dojo nothing special has to be considered. It seems to work out of the box. Just create a dedicated `dojo` user and run rootless mode in it.

For mempool do the same + change the ownership of some folders. I can provide the necessary steps here or create a repo and invite you...

**Comment by RequestPrivacy** [comment]
For mempool it would be the following.  Note that I don't have a rootfull docker on my system, I don't know how they would interact with each other.

- Create a new unprivileged user (`mempool`  in here) and install rootless docker and switch (see the guide I've mentioned above)

**In the unprivileged user:**
- Clone mempool repo 
  
  ```bash
  git clone https://github.com/mempool/mempool.git
  ```

- Go to the docker folder
  
  ```bash
  cd mempool/docker
  ```

- Edit docker-compose.yml according to the guide you follow or the settings you neeed. You have to change the port to something above 1024. Don't let it remain at port 80!
  
  ```bash
  nano docker-compose.yml
  ```
  
  ```yaml
  version: "3.7"
  
  services:
    web:
      environment:
        FRONTEND_HTTP_PORT: "8080"
        BACKEND_MAINNET_HTTP_HOST: "api"
      image: mempool/frontend:latest
      user: "1000:1000"
      restart: on-failure
      stop_grace_period: 1m
      command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
      ports:
        - 80:8080 #<-------change port 80 to something above 1024!!!
  ```

- Mempool runs its container with a container user id of `uid=1000`, compare following line in the `docker-compose.yml` file:
  
  ```yml
    api:
      ...
      user: "1000:1000" #<---- runs with uid 1000
      ...
      volumes:
        - ./data:/backend/cache #<--- ./data folder on host must be read and writable for container user uid 1000
    db:
      ...
      user: "1000:1000" #<---- runs with uid 1000
      ...
      volumes:
        - ./mysql/data:/var/lib/mysql #<--- ./mysql/data on the host must be read and writable for container user uid 1000
  ```
  
To be able to write to the container on the host `pathToYourMempoolFolder/docker/data/` and `pathToYourMempoolFolder/docker/mysql/data`  and its subfolders must be owned by the user who has `uid=1000` in the container. 
  
  Run
  
  ```bash
  cat /etc/subuid
  ...
  mempool:362144:65536
  ...
  ```
  
User `mempool` has subids staring at 362.144. If the container assigns a `uid=1000` that means the user who accesses the mentioned folders above from the *host perspective* is user with `uid=`362.144 + 999 = 363143 (note, uid=1 is 362.144, to get to uid=1000 we need only add 999, not 1000 to 362.144). Your numbers might be different. Just add 999 to the bigger number that gets printed for the mempool user.
  
  To change the ownership of both folders and any subfolders:
  
  ```bash
  # go back to sudo admin account and change ownership
  sudo chown -R 363143:363143 pathToYourMempoolFolder/docker/data pathToYourMempoolFolder/docker/mysql
  # switch back to mempool user
  sudo su - mempool
  ```

- Run mempool
  
 ```bash
  docker compose up -d
  # See the logs
  docker compose logs -f
  ```
